# Generated by Django 4.1.7 on 2023-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_loan',
            fields=[
                ('home_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('cibil_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_home_loan_scheme',
            },
        ),
    ]
