# Generated by Django 4.1.7 on 2023-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0002_home_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_loan',
            name='cibil_score',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
