# Generated by Django 4.1.7 on 2023-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_alter_home_loan_cibil_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='education_loan',
            fields=[
                ('education_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_limit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_edu_loan_scheme',
            },
        ),
    ]
