# Generated by Django 4.1.7 on 2023-03-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_education_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_loan',
            fields=[
                ('vehicle_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('cibil_score', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_vehicle_loan_scheme',
            },
        ),
    ]
