# Generated by Django 4.1.7 on 2023-03-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_vehicle_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_loan',
            fields=[
                ('personal_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('cibil_score', models.CharField(max_length=50)),
                ('loan_limit', models.IntegerField()),
                ('Tenure', models.IntegerField()),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'tbl_personal_loan_scheme',
            },
        ),
    ]
