# Generated by Django 4.1.7 on 2023-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0006_personal_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('mail_id', models.CharField(max_length=50)),
                ('photo', models.CharField(default='nil', max_length=50)),
                ('identity_proof', models.CharField(default='nil', max_length=50)),
                ('gender', models.CharField(default='nil', max_length=50)),
                ('marital_status', models.CharField(default='nil', max_length=50)),
                ('dob', models.DateField()),
                ('spouse', models.CharField(default='nil', max_length=50)),
                ('no_dependents', models.IntegerField(default=0)),
                ('no_childen', models.CharField(default=0, max_length=50)),
                ('caste_category', models.CharField(default='nil', max_length=50)),
                ('nationality', models.CharField(default='nil', max_length=50)),
                ('residential_status', models.CharField(default='nil', max_length=50)),
                ('place_of_birth', models.CharField(default='nil', max_length=50)),
                ('pan_no', models.CharField(default='nil', max_length=50)),
                ('highest_qualification', models.CharField(default='nil', max_length=50)),
                ('city', models.CharField(default='nil', max_length=50)),
                ('district', models.CharField(default='nil', max_length=50)),
                ('occupation', models.CharField(default='nil', max_length=50)),
                ('income', models.IntegerField(default=0)),
                ('status', models.CharField(default='No Updated', max_length=50)),
                ('itr', models.CharField(default='Nil', max_length=50)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
    ]
