# Generated by Django 4.1.7 on 2023-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0007_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
