# Generated by Django 4.1.7 on 2023-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0009_alter_user_register_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_education_loan',
            fields=[
                ('appl_edu_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone_number', models.BigIntegerField()),
                ('highest_qualification', models.CharField(max_length=50)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('address', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('Institution', models.CharField(max_length=50)),
                ('expected_income', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_application_edu_loan',
            },
        ),
        migrations.CreateModel(
            name='application_home_loan',
            fields=[
                ('appl_home_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('address', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('loan_purpose', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_application_home_loan',
            },
        ),
        migrations.CreateModel(
            name='application_personal_loan',
            fields=[
                ('appl_personal_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bank_statement', models.CharField(max_length=50)),
                ('salary_slip', models.CharField(max_length=50)),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_application_personal_loan',
            },
        ),
        migrations.CreateModel(
            name='application_vehicle_loan',
            fields=[
                ('appl_vehicle_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('vmodel', models.CharField(max_length=50)),
                ('Supplier', models.CharField(max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dpayment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tenure', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user_login_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_application_vehicle_loan',
            },
        ),
        migrations.AlterField(
            model_name='user_register',
            name='dob',
            field=models.DateField(default='2023-03-03'),
        ),
    ]
