# Generated by Django 4.1.7 on 2023-03-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0011_application_education_loan_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_education_loan',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_education_loan',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
