# Generated by Django 4.1.7 on 2023-03-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0012_application_education_loan_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=50)),
                ('reply', models.CharField(default='Nil', max_length=50)),
                ('user_login_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
    ]
