# Generated by Django 4.1.7 on 2023-03-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0013_complaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='complaints',
        ),
    ]
