# Generated by Django 4.1.7 on 2023-03-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0015_application_home_loan_allowed_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_home_loan',
            name='Tenure',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
