# Generated by Django 4.1.7 on 2023-03-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0016_application_home_loan_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_education_loan',
            name='Tenure',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application_education_loan',
            name='allowed_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='application_education_loan',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application_education_loan',
            name='repayment_date',
            field=models.DateField(default='2023-03-03'),
        ),
    ]
