# Generated by Django 4.1.7 on 2023-03-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0019_application_personal_loan_allowed_loan_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_loan_payment',
            fields=[
                ('home_loan_payment_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('duedate', models.DateField(max_length=50)),
                ('principle_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_home_loan_payment',
            },
        ),
    ]
