# Generated by Django 4.1.7 on 2023-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0020_home_loan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_loan_payment',
            name='appl_home_loan_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
