# Generated by Django 4.1.7 on 2023-03-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0021_home_loan_payment_appl_home_loan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_payment',
            fields=[
                ('loan_payment_loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('duedate', models.DateField(max_length=50)),
                ('principle_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_loan_payment',
            },
        ),
        migrations.DeleteModel(
            name='home_loan_payment',
        ),
    ]
