# Generated by Django 4.1.7 on 2023-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0022_loan_payment_delete_home_loan_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_payment',
            name='current_principal_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
